# -*- coding: utf-8 -*-
"""67160216 iot week2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1T-K3tQYDclnS-xhsLOGY6Z1TED2IBpoJ

1.กำหนด Data Quality Rules และระบุปัญหาในแต่ละแถว
ก่อนเริ่มต้นทำความสะอาด เราจะเขียนโค้ดตรวจสอบเพื่อระบุปัญหาคุณภาพข้อมูลในแต่ละแถว โดยบันทึกปัญหาลงในคอลัมน์ issues เพื่อตรวจสอบว่าข้อมูลแถวใดมีปัญหาอะไรบ้าง
"""

import numpy as np
import pandas as pd

# 1. โหลดข้อมูลดิบ (Raw Data)
df = pd.read_csv("iot_sensor_raw_data_extended.csv")

# 2. ค้นหาแถวที่มีข้อมูลซ้ำ (Duplicate) บนคู่ของ device_id และ timestamp
dup_mask = (
    df.duplicated(subset=["device_id", "timestamp"], keep=False)
    & df["device_id"].notnull()
)

# --- เพิ่มตัวนับยอดสะสมของแต่ละ Error ---
error_counts = {
    "temp_null": 0,
    "temp_out_of_range": 0,
    "device_id_null": 0,
    "duplicate": 0,
    "battery_null": 0,
    "battery_out_of_range": 0,
}

# 3. ตรวจสอบคุณภาพข้อมูลทีละแถว (Row-by-Row Check)
issues_log = []

for idx, row in df.iterrows():
    row_errors = []

    # กฎข้อที่ 1: ตรวจสอบอุณหภูมิ (0–50 °C)
    if pd.isnull(row["temp_c"]):
        row_errors.append("temp_c is NULL")
        error_counts["temp_null"] += 1
    elif row["temp_c"] < 0 or row["temp_c"] > 50:
        row_errors.append(f"temp_c out of range ({row['temp_c']})")
        error_counts["temp_out_of_range"] += 1

    # กฎข้อที่ 2: device_id ห้ามเป็นค่าว่าง
    if pd.isnull(row["device_id"]):
        row_errors.append("device_id is NULL")
        error_counts["device_id_null"] += 1

    # กฎข้อที่ 3: ห้ามมีข้อมูลซ้ำที่มี device_id และ timestamp เดียวกัน
    if dup_mask[idx]:
        row_errors.append("duplicate device_id + timestamp")
        error_counts["duplicate"] += 1

    # กฎข้อที่ 4: ตรวจสอบแบตเตอรี่ (0–100)
    if pd.isnull(row["battery"]):
        row_errors.append("battery is NULL")
        error_counts["battery_null"] += 1
    elif row["battery"] < 0 or row["battery"] > 100:
        row_errors.append(f"battery out of range ({row['battery']})")
        error_counts["battery_out_of_range"] += 1

    # หากแถวนั้นพบ Error ให้บันทึกเก็บไว้
    if row_errors:
        issues_log.append(
            {
                "Row_Index": idx,
                "Timestamp": row["timestamp"],
                "Device_ID": row["device_id"],
                "Errors": row_errors,
                "Error_Count": len(row_errors),
            }
        )

# แปลงผลลัพธ์เป็น DataFrame
issues_df = pd.DataFrame(issues_log)

# --- ส่วนแสดงรายงานสรุปคุณภาพข้อมูล ---

# 1) แสดงตัวอย่างแถวที่มีปัญหา
print("=== ตัวอย่าง 15 แถวแรกที่พบปัญหาคุณภาพข้อมูล ===")
print(
    issues_df[["Row_Index", "Timestamp", "Device_ID", "Errors", "Error_Count"]]
    .head(15)
    .to_string(index=False)
)
print("\n" + "=" * 80 + "\n")

# 2) สรุปยอดรวมจำนวนปัญหาแต่ละประเภทตามกฎ Data Quality Rules
total_errors_detected = sum(error_counts.values())

print("สรุปผลสรุปจำนวนความผิดพลาดแยกตามกฎ (Data Quality Summary)")
print(
    f"1. กฎอุณหภูมิ (ต้องอยู่ระหว่าง 0-50 องศาเซลเซียส)\n"
    f"   อุณหภูมิเป็นค่าว่าง (NULL): {error_counts['temp_null']} ตัว\n"
    f"    อุณหภูมิหลุดนอกช่วงที่กำหนด (0-50): {error_counts['temp_out_of_range']} ตัว\n"
)
print(
    f"2. กฎรหัสอุปกรณ์ (device_id ห้ามเป็นค่าว่าง)\n"
    f"    device_id เป็นค่าว่าง (NULL): {error_counts['device_id_null']} ตัว\n"
)
print(
    f"3. กฎข้อมูลห้ามซ้ำซ้อน (device_id และ timestamp เดียวกัน)\n"
    f"    ข้อมูลส่งซ้ำซ้อนในระบบ: {error_counts['duplicate']} ตัว\n"
)
print(
    f"4. กฎค่าแบตเตอรี่ (ต้องอยู่ระหว่าง 0-100)\n"
    f"   แบตเตอรี่เป็นค่าว่าง (NULL): {error_counts['battery_null']} ตัว\n"
    f"   แบตเตอรี่หลุดนอกช่วงที่กำหนด (0-100): {error_counts['battery_out_of_range']} ตัว\n"
)
print("-" * 50)
print(f"จำนวนครั้งที่ละเมิดกฎทั้งหมด (Total Error Triggers): {total_errors_detected} ครั้ง")
print(f"จำนวนแถวที่มีปัญหาทั้งหมด: {len(issues_df)} จากทั้งหมด {len(df)} แถว")

"""หัวข้อที่ 2: การทำความสะอาดข้อมูล (Data Cleaning)
โค้ดในส่วนนี้จะดำเนินการคลีนข้อมูลตามโจทย์: ลบข้อมูลซ้ำ, แปลงค่าผิดปกติเป็น NULL (NaN), จัดการ Missing Value และสร้างคอลัมน์บอกสถานะ
"""

# คัดลอกข้อมูลมาทำความสะอาดเพื่อไม่ให้กระทบ Raw Data ต้นฉบับ
df_cleaned = df.copy()

# 1. ลบข้อมูลซ้ำ (ลบแถวที่ device_id และ timestamp ซ้ำกัน โดยเก็บแถวแรกไว้)
df_cleaned.drop_duplicates(
    subset=["device_id", "timestamp"], keep="first", inplace=True
)

# 2. จัดการ Missing Value (ในกรณีที่ device_id เป็นค่าว่าง จะลบแถวนั้นออกเพราะเป็น Key สำคัญ)
df_cleaned.dropna(subset=["device_id"], inplace=True)

# 3. แปลงค่าผิดปกติ (Outliers) ให้เป็น NULL (NaN) ตามกฎ Data Quality
df_cleaned.loc[
    (df_cleaned["temp_c"] < 0) | (df_cleaned["temp_c"] > 50), "temp_c"
] = np.nan
df_cleaned.loc[
    (df_cleaned["battery"] < 0) | (df_cleaned["battery"] > 100), "battery"
] = np.nan

# 4. จัดการ Missing Value ที่เหลือ (เช่น การกรอกค่าเฉลี่ยแทนที่ค่าที่เป็น NULL)
# ในที่นี้เราจะกรอกค่าเฉลี่ย (Mean) ของแต่ละอุปกรณ์ หรือเติมค่าอุณหภูมิมาตรฐานเข้าไป
df_cleaned["temp_c"] = df_cleaned["temp_c"].fillna(df_cleaned["temp_c"].mean())
df_cleaned["battery"] = df_cleaned["battery"].fillna(
    df_cleaned["battery"].mean()
)
df_cleaned["motion"] = df_cleaned["motion"].fillna(
    "unknown"
)  # สำหรับข้อมูลประเภทข้อความ


# 5. เพิ่มคอลัมน์ data_quality_status
# สร้างฟังก์ชันเช็คสถานะว่าแถวใดผ่านการปรับปรุงข้อมูลมาบ้าง
def check_quality_status(row_idx):
    if row_idx in issues_df["Row_Index"].values:
        return "Cleaned & Rectified"
    return "Passed (Perfect)"


df_cleaned["data_quality_status"] = df_cleaned.index.map(check_quality_status)

print("ตัวอย่างข้อมูลหลังทำความสะอาดสำเร็จ")
print(df_cleaned.head(10))

"""หัวข้อที่ 3: เปรียบเทียบจำนวนแถวก่อนและหลังทำความสะอาด


"""

row_count_after = len(df_cleaned)
rows_removed = row_count_before - row_count_after

print("=== สรุปผลการเปรียบเทียบข้อมูล ===")
summary_table = pd.DataFrame(
    {
        "รายการ": [
            "จำนวนแถวก่อนคลีน (Raw Data)",
            "จำนวนแถวหลังคลีน (Cleaned Data)",
            "จำนวนแถวที่ถูกลบออก (ซ้ำ/Missing ID)",
        ],
        "จำนวน (แถว)": [row_count_before, row_count_after, rows_removed],
    }
)
print(summary_table.to_string(index=False))